<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $countries = [
            ["MADAGASCAR", "MG", "MGA"],
            ["ARGENTINA", "AR", "ARS"],
            ["ARMENIA", "AM", "AMD"],
            ["ARUBA", "AW", "AWG"],
            ["AUSTRALIA", "AU", "AUD"],
            ["CHRISTMAS ISLAND", "CX", "AUD"],
            ["COCOS (KEELING) ISLANDS", "CC", "AUD"],
            ["HEARD ISLAND AND MCDONALD ISLANDS", "HM", "AUD"],
            ["KIRIBATI", "KI", "AUD"],
            ["NAURU", "NR", "AUD"],
            ["NORFOLK ISLAND", "NF", "AUD"],
            ["TUVALU", "TV", "AUD"],
            ["AZERBAIJAN", "AZ", "AZM"],
            ["BAHAMAS", "BS", "BSD"],
            ["BAHRAIN", "BH", "BHD"],
            ["THAILAND", "TH", "THB"],
            ["PANAMA", "PA", "PAB"],
            ["BARBADOS", "BB", "BBD"],
            ["BELARUS", "BY", "BYR"],
            ["BELIZE", "BZ", "BZD"],
            ["BERMUDA", "BM", "BMD"],
            ["VENEZUELA", "VE", "VEB"],
            ["BOLIVIA", "BO", "BOB"],
            ["BRAZIL", "BR", "BRL"],
            ["BRUNEI DARUSSALAM", "BN", "BND"],
            ["BULGARIA", "BG", "BGN"],
            ["BURUNDI", "BI", "BIF"],
            ["CANADA", "CA", "CAD"],
            ["CAPE VERDE", "CV", "CVE"],
            ["CAYMAN ISLANDS", "KY", "KYD"],
            ["GHANA", "GH", "GHC"],
            ["BENIN", "BJ", "XOF"],
            ["BURKINA FASO", "BF", "XOF"],
            ["COTE D'IVOIRE", "CI", "XOF"],
            ["GUINEA-BISSAU", "GW", "XOF"],
            ["MALI", "ML", "XOF"],
            ["NIGER", "NE", "XOF"],
            ["SENEGAL", "SN", "XOF"],
            ["TOGO", "TG", "XOF"],
            ["CAMEROON", "CM", "XAF"],
            ["CENTRAL AFRICAN REPUBLIC", "CF", "XAF"],
            ["CHAD", "TD", "XAF"],
            ["CONGO", "CG", "XAF"],
            ["EQUATORIAL GUINEA", "GQ", "XAF"],
            ["GABON", "GA", "XAF"],
            ["FRENCH POLYNESIA", "PF", "XPF"],
            ["NEW CALEDONIA", "NC", "XPF"],
            ["WALLIS AND FUTUNA", "WF", "XPF"],
            ["CHILE", "CL", "CLP"],
            ["COLOMBIA", "CO", "COP"],
            ["COMOROS", "KM", "KMF"],
            ["BOSNIA AND HERZEGOVINA", "BA", "BAM"],
            ["NICARAGUA", "NI", "NIO"],
            ["COSTA RICA", "CR", "CRC"],
            ["CROATIA", "HR", "HRK"],
            ["CUBA", "CU", "CUP"],
            ["CYPRUS", "CY", "CYP"],
            ["CZECH REPUBLIC", "CZ", "CZK"],
            ["GAMBIA", "GM", "GMD"],
            ["DENMARK", "DK", "DKK"],
            ["FAROE ISLANDS", "FO", "DKK"],
            ["GREENLAND", "GL", "DKK"],
            ["MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF", "MK", "MKD"],
            ["DJIBOUTI", "DJ", "DJF"],
            ["SAO TOME AND PRINCIPE", "ST", "STD"],
            ["DOMINICAN REPUBLIC", "DO", "DOP"],
            ["VIET NAM", "VN", "VND"],
            ["DOMINICA", "DM", "XCD"],
            ["GRENADA", "GD", "XCD"],
            ["MONTSERRAT", "MS", "XCD"],
            ["SAINT KITTS AND NEVIS", "KN", "XCD"],
            ["SAINT LUCIA", "LC", "XCD"],
            ["SAINT VINCENT AND THE GRENADINES", "VC", "XCD"],
            ["ANGUILLA", "AI", "XCD"],
            ["ANTIGUA AND BARBUDA", "AG", "XCD"],
            ["EGYPT", "EG", "EGP"],
            ["EL SALVADOR", "SV", "SVC"],
            ["ETHIOPIA", "ET", "ETB"],
            ["ANDORRA", "AD", "EUR"],
            ["AUSTRIA", "AT", "EUR"],
            ["BELGIUM", "BE", "EUR"],
            ["FINLAND", "FI", "EUR"],
            ["FRANCE", "FR", "EUR"],
            ["FRENCH GUIANA", "GF", "EUR"],
            ["FRENCH SOUTHERN TERRITORIES", "TF", "EUR"],
            ["GERMANY", "DE", "EUR"],
            ["GREECE", "GR", "EUR"],
            ["GUADELOUPE", "GP", "EUR"],
            ["HOLY SEE (VATICAN CITY STATE)", "VA", "EUR"],
            ["IRELAND", "IE", "EUR"],
            ["ITALY", "IT", "EUR"],
            ["LUXEMBOURG", "LU", "EUR"],
            ["MARTINIQUE", "MQ", "EUR"],
            ["MAYOTTE", "YT", "EUR"],
            ["MONACO", "MC", "EUR"],
            ["NETHERLANDS", "NL", "EUR"],
            ["PORTUGAL", "PT", "EUR"],
            ["REUNION", "RE", "EUR"],
            ["SAINT PIERRE AND MIQUELON", "PM", "EUR"],
            ["SAN MARINO", "SM", "EUR"],
            ["SERBIA & MONTENEGRO", "CS", "EUR"],
            ["SPAIN", "ES", "EUR"],
            ["FALKLAND ISLANDS (MALVINAS)", "FK", "FKP"],
            ["FIJI", "FJ", "FJD"],
            ["HUNGARY", "HU", "HUF"],
            ["CONGO, THE DEMOCRATIC REPUBLIC OF THE", "CD", "CDF"],
            ["GIBRALTAR", "GI", "GIP"],
            ["HAITI", "HT", "HTG"],
            ["PARAGUAY", "PY", "PYG"],
            ["GUINEA", "GN", "GNF"],
            ["GUINEA-BISSAU", "GW", "GWP"],
            ["GUYANA", "GY", "GYD"],
            ["HONG KONG", "HK", "HKD"],
            ["UKRAINE", "UA", "UAH"],
            ["ICELAND", "IS", "ISK"],
            ["BHUTAN", "BT", "INR"],
            ["INDIA", "IN", "INR"],
            ["IRAN, ISLAMIC REPUBLIC OF", "IR", "IRR"],
            ["IRAQ", "IQ", "IQD"],
            ["JAMAICA", "JM", "JMD"],
            ["JORDAN", "JO", "JOD"],
            ["KENYA", "KE", "KES"],
            ["PAPUA NEW GUINEA", "PG", "PGK"],
            ["LAO PEOPLE'S DEMOCRATIC REPUBLIC", "LA", "LAK"],
            ["ESTONIA", "EE", "EEK"],
            ["KUWAIT", "KW", "KWD"],
            ["MALAWI", "MW", "MWK"],
            ["ZAMBIA", "ZM", "ZMK"],
            ["ANGOLA", "AO", "AOA"],
            ["MYANMAR", "MM", "MMK"],
            ["GEORGIA", "GE", "GEL"],
            ["LATVIA", "LV", "LVL"],
            ["LEBANON", "LB", "LBP"],
            ["ALBANIA", "AL", "ALL"],
            ["HONDURAS", "HN", "HNL"],
            ["SIERRA LEONE", "SL", "SLL"],
            ["ROMANIA", "RO", "ROL"],
            ["BULGARIA", "BG", "BGL"],
            ["LIBERIA", "LR", "LRD"],
            ["SWAZILAND", "SZ", "SZL"],
            ["LITHUANIA", "LT", "LTL"],
            ["LESOTHO", "LS", "LSL"],
            ["LIBYAN ARAB JAMAHIRIYA", "LY", "LYD"],
            ["MADAGASCAR", "MG", "MGF"],
            ["MALAYSIA", "MY", "MYR"],
            ["MALTA", "MT", "MTL"],
            ["TURKMENISTAN", "TM", "TMM"],
            ["MAURITIUS", "MU", "MUR"],
            ["MOZAMBIQUE", "MZ", "MZM"],
            ["MEXICO", "MX", "MXN"],
            ["MEXICO", "MX", "MXV"],
            ["MOLDOVA, REPUBLIC OF", "MD", "MDL"],
            ["MOROCCO", "MA", "MAD"],
            ["WESTERN SAHARA", "EH", "MAD"],
            ["BOLIVIA", "BO", "BOV"],
            ["NIGERIA", "NG", "NGN"],
            ["ERITREA", "ER", "ERN"],
            ["NAMIBIA", "NA", "NAD"],
            ["NEPAL", "NP", "NPR"],
            ["NETHERLANDS ANTILLES", "AN", "ANG"],
            ["ISRAEL", "IL", "ILS"],
            ["TAIWAN, PROVINCE OF CHINA", "TW", "TWD"],
            ["COOK ISLANDS", "CK", "NZD"],
            ["NEW ZEALAND", "NZ", "NZD"],
            ["NIUE", "NU", "NZD"],
            ["PITCAIRN", "PN", "NZD"],
            ["TOKELAU", "TK", "NZD"],
            ["BHUTAN", "BT", "BTN"],
            ["ANTARCTICA", "AQ", ""],
            ["KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF", "KP", "KPW"],
            ["BOUVET ISLAND", "BV", "NOK"],
            ["NORWAY", "NO", "NOK"],
            ["SVALBARD AND JAN MAYEN", "SJ", "NOK"],
            ["PERU", "PE", "PEN"],
            ["MAURITANIA", "MR", "MRO"],
            ["TONGA", "TO", "TOP"],
            ["PAKISTAN", "PK", "PKR"],
            ["MACAO", "MO", "MOP"],
            ["URUGUAY", "UY", "UYU"],
            ["PHILIPPINES", "PH", "PHP"],
            ["UNITED KINGDOM", "GB", "GBP"],
            ["BOTSWANA", "BW", "BWP"],
            ["QATAR", "QA", "QAR"],
            ["GUATEMALA", "GT", "GTQ"],
            ["LESOTHO", "LS", "ZAR"],
            ["NAMIBIA", "NA", "ZAR"],
            ["SOUTH AFRICA", "ZA", "ZAR"],
            ["OMAN", "OM", "OMR"],
            ["CAMBODIA", "KH", "KHR"],
            ["MALDIVES", "MV", "MVR"],
            ["INDONESIA", "ID", "IDR"],
            ["RUSSIAN FEDERATION", "RU", "RUB"],
            ["RUSSIAN FEDERATION", "RU", "RUR"],
            ["RWANDA", "RW", "RWF"],
            ["SAINT HELENA", "SH", "SHP"],
            ["SAUDI ARABIA", "SA", "SAR"],
            ["SERBIA & MONTENEGRO", "CS", "CSD"],
            ["SEYCHELLES", "SC", "SCR"],
            ["SINGAPORE", "SG", "SGD"],
            ["SLOVAKIA", "SK", "SKK"],
            ["SOLOMON ISLANDS", "SB", "SBD"],
            ["KYRGYZSTAN", "KG", "KGS"],
            ["SOMALIA", "SO", "SOS"],
            ["TAJIKISTAN", "TJ", "TJS"],
            ["SRI LANKA", "LK", "LKR"],
            ["SUDAN", "SD", "SDD"],
            ["SURINAME", "SR", "SRD"],
            ["SWEDEN", "SE", "SEK"],
            ["LIECHTENSTEIN", "LI", "CHF"],
            ["SWITZERLAND", "CH", "CHF"],
            ["SYRIAN ARAB REPUBLIC", "SY", "SYP"],
            ["BANGLADESH", "BD", "BDT"],
            ["SAMOA", "WS", "WST"],
            ["TANZANIA, UNITED REPUBLIC OF", "TZ", "TZS"],
            ["KAZAKHSTAN", "KZ", "KZT"],
            ["SLOVENIA", "SI", "SIT"],
            ["TRINIDAD AND TOBAGO", "TT", "TTD"],
            ["MONGOLIA", "MN", "MNT"],
            ["TUNISIA", "TN", "TND"],
            ["TURKEY", "TR", "TRL"],
            ["UNITED ARAB EMIRATES", "AE", "AED"],
            ["UGANDA", "UG", "UGX"],
            ["ECUADOR", "EC", "ECV"],
            ["CHILE", "CL", "CLF"],
            ["AMERICAN SAMOA", "AS", "USD"],
            ["BRITISH INDIAN OCEAN TERRITORY", "IO", "USD"],
            ["ECUADOR", "EC", "USD"],
            ["EL SALVADOR", "SV", "USD"],
            ["GUAM", "GU", "USD"],
            ["HAITI", "HT", "USD"],
            ["MARSHALL ISLANDS", "MH", "USD"],
            ["MICRONESIA, FEDERATED STATES OF", "FM", "USD"],
            ["NORTHERN MARIANA ISLANDS", "MP", "USD"],
            ["PALAU", "PW", "USD"],
            ["PANAMA", "PA", "USD"],
            ["PUERTO RICO", "PR", "USD"],
            ["TIMOR-LESTE", "TL", "USD"],
            ["TURKS AND CAICOS ISLANDS", "TC", "USD"],
            ["UNITED STATES", "US", "USD"],
            ["UNITED STATES MINOR OUTLYING ISLANDS", "UM", "USD"],
            ["VIRGIN ISLANDS, BRITISH", "VG", "USD"],
            ["VIRGIN ISLANDS, U.S.", "VI", "USD"],
            ["UNITED STATES", "US", "USN"],
            ["UNITED STATES", "US", "USS"],
            ["UZBEKISTAN", "UZ", "UZS"],
            ["VANUATU", "VU", "VUV"],
            ["KOREA, REPUBLIC OF", "KR", "KRW"],
            ["YEMEN", "YE", "YER"],
            ["JAPAN", "JP", "JPY"],
            ["CHINA", "CN", "CNY"],
            ["ZIMBABWE", "ZW", "ZWD"],
            ["POLAND", "PL", "PLN"],
        ];
        foreach ($countries as $country) {
            Country::factory()->state(
                ['name' => $country[0], 'country_code' => $country[1], 'currency_default' => $country[2]]
            )->create();
        }
    }
}
