<?php

namespace App\Repositories;

use Illuminate\Database\Eloquent\Model;

class PersonEloquentRepository extends EloquentRepository
{
    public function create(Model|array $model)
    {
        parent::create($model); // TODO: Change the autogenerated stub
    }

    public function delete(int $id)
    {
        parent::delete($id); // TODO: Change the autogenerated stub
    }

    public function find(int $id)
    {
        parent::find($id); // TODO: Change the autogenerated stub
    }

    public function update(int $id, Model|array $model)
    {
        parent::update($id, $model); // TODO: Change the autogenerated stub
    }

}